# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e877caa5d92a30a5a3277fb5b0450344e33d458f3722f5e8e4f687af82bddcd0181dbfa79f7fa688d19d3b25d7d4c355f705a5bdeb52d117dee29b7aa11900f2

test:
  secret_key_base: d86f3fc2d3f6e48a9becb7ffe14539e64b72b647674b5f0ddbdc8542fc1111eca1f2f8b96e3c290e7c1d72eae36c96318ae2de58aa8591a28841f9edf540f672

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
